name: Main

on:
  push:
    branches: [ master ]

env:
  VERSION_PREFIX: "1.0"
  NAME: "container-stack-containerisedapprepository181f38df-qmk6dzgbaa3p"
  ECR: "906440755908.dkr.ecr.eu-central-1.amazonaws.com"

jobs:    
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Package Image
      run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $ECR
          docker build -t $NAME .
          docker tag $NAME $ECR/$NAME:$VERSION_PREFIX.$GITHUB_RUN_NUMBER
          docker tag $NAME $ECR/$NAME:latest
          docker push $ECR/$NAME:$VERSION_PREFIX.$GITHUB_RUN_NUMBER
          docker push $ECR/$NAME:latest
          echo "$ECR/$NAME:$VERSION_PREFIX.$GITHUB_RUN_NUMBER published"